rebase before push
git push ***github.com/orange-cloudfoundry/k3s-boshrelease.git HEAD:main
To https://github.com/orange-cloudfoundry/k3s-boshrelease.git
 ! [rejected]        HEAD -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/orange-cloudfoundry/k3s-boshrelease.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.